# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_Z <- function(Z, delta, Lambda, U, Sigma, invD, X, beta) {
    .Call(`_scFM_sample_Z`, Z, delta, Lambda, U, Sigma, invD, X, beta)
}

sample_delta <- function(delta, Z, X, beta) {
    .Call(`_scFM_sample_delta`, delta, Z, X, beta)
}

sample_Lambda <- function(Z, U, Sigma, Phi, tau, Psi) {
    .Call(`_scFM_sample_Lambda`, Z, U, Sigma, Phi, tau, Psi)
}

sample_U <- function(Z, Lambda, invSigma) {
    .Call(`_scFM_sample_U`, Z, Lambda, invSigma)
}

sample_Phi <- function(Lambda, alpha) {
    .Call(`_scFM_sample_Phi`, Lambda, alpha)
}

sample_c <- function(U, pi, mu) {
    .Call(`_scFM_sample_c`, U, pi, mu)
}

sample_mu_pi <- function(U, c, phi, H, alpha) {
    .Call(`_scFM_sample_mu_pi`, U, c, phi, H, alpha)
}

